# Generated by Django 3.2.4 on 2021-10-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('aboutme', models.CharField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music1', models.CharField(max_length=25)),
                ('music2', models.CharField(max_length=25)),
                ('music3', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MusicsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music1about', models.CharField(max_length=25)),
                ('music2about', models.CharField(max_length=25)),
                ('music3about', models.CharField(max_length=25)),
            ],
        ),
    ]
