# Generated by Django 3.2.4 on 2021-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeinsite', '0004_auto_20211013_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='spotify',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
