# Generated by Django 3.2.4 on 2021-10-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moeinsite', '0005_info_spotify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='info',
            name='instagrm',
        ),
        migrations.RemoveField(
            model_name='info',
            name='spotify',
        ),
        migrations.RemoveField(
            model_name='info',
            name='youtube',
        ),
    ]
