# Generated by Django 3.2.4 on 2021-10-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeinsite', '0006_auto_20211013_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='facebookchat',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
