# Generated by Django 3.2.4 on 2021-10-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeinsite', '0007_info_facebookchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='aboutmetwo',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
