# Generated by Django 3.2.4 on 2021-10-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeinsite', '0008_info_aboutmetwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='music4',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='musics',
            name='music1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='musics',
            name='music2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='musics',
            name='music3',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
