# Generated by Django 3.2.4 on 2021-10-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeinsite', '0009_auto_20211013_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='aboutmusics',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
