# Generated by Django 3.2.4 on 2021-10-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moeinsite', '0011_sendmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
